### ISSUE TITLE
Not able to run this in sails 

### ISSUE THREAD

**Issue by echorohit** [request/request-debug#2]
Hi,
I want to log my request using  request debug module. I have installed in globally in my system as I dont want this on my server. But when I am  doing this require('request-debug')(request); is gives me error

```
Error: Cannot find module 'request-debug'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rohit/reincarnation/frontend/api/controllers/CartController.js:13:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/rohit/reincarnation/frontend/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/home/rohit/reincarnation/frontend/node_modules/include-all/index.js:44:9)
    at buildDictionary (/home/rohit/reincarnation/frontend/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/home/rohit/reincarnation/frontend/node_modules/sails/node_modules/sails-build-dictionary/index.js:160:9)
```

**Comment by simov** [comment]
Well, for some reason `request-debug` isn't found, try to install it where you project is.

**Comment by echorohit** [comment]
I can not add this into my project

**Comment by nylen** [comment]
> I have installed in globally in my system as I dont want this on my server.

You can't `require` a package that is installed globally.  You need to `npm install` it into your project or it won't work.
